version: '3.7'

services:
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass senocak
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - ops
  mongo:
    image: mongo:6.0.3
    ports:
      - '27017:27017'
    container_name: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anil
      - MONGO_INITDB_ROOT_PASSWORD=senocak
    networks:
      - ops
volumes:
  redis-data:
networks:
  ops: